source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AsyncLoadLocalImage_Example', :exclusive => true do
  pod 'AsyncLoadLocalImage', :path => '../'
end

target 'AsyncLoadLocalImage_Tests', :exclusive => true do
  pod 'AsyncLoadLocalImage', :path => '../'

  pod 'FBSnapshotTestCase'
end
