source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'AsyncLoadLocalImage_Example' do
  pod 'AsyncLoadLocalImage', :path => '../'
end

target 'AsyncLoadLocalImage_Tests' do
  pod 'AsyncLoadLocalImage', :path => '../'
end
